### ISSUE TITLE
Files incorrectly parsed as llanfair

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [LiveSplit/livesplit-core#108]
It seems that all binary files are being detected as llanfair regardless of if they are actually valid files or not.  One example is a file of all null bytes (cryze thinks this might be a livesplit upload bug but the point still stands) and another will be linked below.

[e3315c3e-fc77-455b-866b-7c4e891561be.zip](https://github.com/LiveSplit/livesplit-core/files/1731994/e3315c3e-fc77-455b-866b-7c4e891561be.zip)

**Comment by hallcristobal** [comment]
It's there any magic word, or specific file structure we could look for?

**Comment by BatedUrGonnaDie** [comment]
I believe all files should start with the following hex values `aced 0005 7372 0016 6f72 672e 6665 6e69 782e 6c6c 616e 6661 6972 2e52 756e`

**Comment by hallcristobal** [comment]
i guess it could be worth checking the whole file for `6f72 672e 6665 6e69 782e 6c6c 616e 6661 6972 2e52 756e` (org.fenix.llanfair.Run) but i feel that would be a bit excessive if it's just at the beginning.

**Comment by BatedUrGonnaDie** [comment]
You could always just trying slicing the string at 100 or so bytes and then just check that for the header stuff if you didn't want to check the whole file.

**Comment by hallcristobal** [comment]
So, it appears that the original llanfair just directly serializes the `Run` object. So in every test I've done it's always started with `AC ED 00 05 73 72 00 16 6F 72 67 2E 66 65 6E 69 78 2E 6C 6C 61 6E 66 61 69 72 2E 52 75 6E` which evaluates to `¬í..sr..org.fenix.llanfair.Run`, so i believe that checking based on that array of bites should be sufficient.

**Comment by CryZe** [comment]
https://docs.oracle.com/javase/7/docs/platform/serialization/spec/protocol.html
```
stream:
    magic: AC ED
    version: 00 05
    contents -> content -> object -> newObject:
        TC_OBJECT: 73
        classDesc -> newClassDesc:
            TC_CLASSDESC: 72
            className -> (utf):
                len: 00 16
                value: org.fenix.llanfair.Run
            ...
```

**Comment by BatedUrGonnaDie** [comment]
I didn't think there would be such an in depth spec on serialization.  Maybe exporting for llanfair might be possible now :O
