### ISSUE TITLE
Possibly parse worstrun splits

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/livesplit-core#111]
There's this new timer: https://github.com/Muffindrake/worstrun

I'm not sure if we want to have some cutoff for too arbitrary / too rarely used timers or if we just want to support everything? It definitely bloats the codebase / final binary a bit.

**Comment by TheEssenceOfDarkness** [comment]
Honestly, I don't think it is even worth the effort seeing that this looks to me more of a small project rather than a fully featured timer.

**Comment by CryZe** [comment]
Well that we should question the others that we have too, as 90% of them are either dead, obscure or don't even work (like Llanfair 2)

**Comment by TheEssenceOfDarkness** [comment]
If we do want to support these timers, what about having support for them optionally compiled in, so whatever is not needed can be excluded from the binary entirely.

**Comment by CryZe** [comment]
Yeah, that's what I thought about too. I wonder if there should be one feature per timer.

**Comment by TheEssenceOfDarkness** [comment]
One feature per timer does seem very reasonable, and in most cases a timer can be left out by default and only compiled in if wanted/needed (as an example splits.io would have support for all timers compiled in, while LiveSplit One would only need a few timers.)
