### ISSUE TITLE
No types definition for typescript on npm

### ISSUE THREAD

**Issue by philippTheCat** [LiveSplit/livesplit-core#125]
Hey there, Im developing an app using typescript, and was trying to download the types definition for typescript. Usually those should be located at @types/<nameofJSpackage>, but @types/livesplit-core does not exist.

Am I doing something wrong/looking at the wrong location?

**Comment by CryZe** [comment]
Yeah, the package on npm doesn't come with the typings atm. We are on it :)

**Comment by CryZe** [comment]
I implemented the typings. Can I just send you the new package so you can see if it works? I can publish a new version afterwards.

**Comment by philippTheCat** [comment]
Sure, that would be lovely.

**Comment by hallcristobal** [comment]
Wasn't this closed in https://github.com/LiveSplit/livesplit-core/commit/e865b4700cb33a2f6367671efaf77151851ac02d ?

**Comment by CryZe** [comment]
Kind of, but I didn't publish a new version yet, so I'd like to keep it open until then.

**Comment by CryZe** [comment]
The latest version comes with the typings :D
