### ISSUE TITLE
Bring back Median Segments

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/livesplit-core#130]
Gabe The Engineer wants it https://twitter.com/gdbassett/status/997199591039754240

**Comment by gdbassett** [comment]
Thank you.  Will this automatically get deployed to http://one.livesplit.org/?

**Comment by CryZe** [comment]
It will once the submodule for LSO gets updated (which I need to do manually). I'll probably work on LSO later today, so I'll probably just update the submodule while doing so.
