### ISSUE TITLE
wayland support for livesplit-hotkey

### ISSUE THREAD

**Issue by lambdadog** [LiveSplit/livesplit-core#140]
currently livesplit-hotkey only works with x11 on linux, which is less than ideal

[inputbot](https://github.com/obv-mikhail/InputBot), another crate that has any global hotkey support (even if it does bring cruft along with it) has moved to libinput as to support x11 and wayland in one go, which would probably be the best direction to go with this

**Comment by beta-phenylethylamine** [comment]
another possible route is to directly use uinput using the [uinput crate](https://docs.rs/uinput/0.1.3/uinput/)

**Comment by xliiv** [comment]
Note that [libinput](https://www.freedesktop.org/wiki/Software/libinput/) requires `sudo`. Also see https://github.com/obv-mikhail/InputBot/issues/14#issuecomment-582777334
On the second thought we're choosing between
- not working in Wayland
- and working in Wayland, but with `sudo`

looks like improvement.

**Comment by TheEssenceOfDarkness** [comment]
Any method that needs root access isn't very desirable here as we don't need to be running as root to begin with. We should look for a solution that doesn't need UID 0.
