### ISSUE TITLE
Turn all TODOs into FIXMEs with links to issues

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/livesplit-core#148]
TODO should be a local reminder that should never make it to master.
FIXME should be a problem that needs to be fixed that has an issue in the repository that it links to.

**Comment by CryZe** [comment]
I feel like this approach is kind of weird in a way, as usually you don't want to create issues about unmerged code, but once it's merged, you don't have any links in there that point to issues. So there's a weird circular dependency in practice.

**Comment by TheEssenceOfDarkness** [comment]
There isn't a single TODO in the codebase at all so I'm guessing this can be closed.

Also see: https://github.com/LiveSplit/livesplit-core/commit/6a99465fa28816342fc2b8c182bc4777f09225f6

**Comment by wooferzfg** [comment]
One of the requirements for closing this issue is making sure that every `FIXME` is linked to an issue, which isn't currently the case.

**Comment by TheEssenceOfDarkness** [comment]
I'll guess I get on that now.

**Comment by TheEssenceOfDarkness** [comment]
Would it be a good idea to have a tracking issue for all of the existing `FIXME`s.

Having a separate issue for every single one of them would get really spammy.

**Comment by CryZe** [comment]
I think you can certainly group a bunch together if they are similar enough to each other. I don't think we want a general one for the ones that are minor and not groupable.
