### ISSUE TITLE
How do I run this on Mac OSX

### ISSUE THREAD

**Issue by Namos0613** [LiveSplit/livesplit-core#158]
I have followed all the instructions and in the "target" directory, I find two folders, debug and release, I assume I should be going into the release folder, but what do I do from there

**Comment by CryZe** [comment]
livesplit-core is just the library that makes up all the logic. The Desktop version of the timer built on top of this (LiveSplit One) isn't really publicly available yet. The Web version however is: https://one.livesplit.org

**Comment by CryZe** [comment]
I'll close this for now, there will be a repository for the desktop version soon.

**Comment by guymaor86** [comment]
any updates on this?
