### ISSUE TITLE
Add record! macro

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/livesplit-core#162]
This is probably very useful for some iterator combinators: https://old.reddit.com/r/rust/comments/ampf8d/personal_collection_of_rust_hacks/efp1cmi/

**Comment by hallcristobal** [comment]
Could be useful for a more in-depth GameState object for Auto Splitters as well. Though might have to cap struct size depending on how people would use it so as to not degrade performance.

**Comment by CryZe** [comment]
I've not really seen much need since. So I'll just close this.
