### ISSUE TITLE
Port PB Chance Component

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/livesplit-core#208]
We might still want to do this. There already is an implementation here https://github.com/CryZe/livesplit-core/tree/pb-chance, but it was too numerically unstable to merge. Maybe we can take an approach similar to Balanced PB where we try to find the percentile that ends up with the PB. The percentile would then be the PB chance. One of the main problems of PB chance is that resets are problematic. I think Sethbling's version makes use of them. But if you do so, your PB chance is always very low, as most runs actually never make it to the end. However not considering the resets also is problematic as most runs that do not actually get reset are probably doing really well, so they are biased towards you actually getting a new Personal Best. However I believe we should go for a PB chance algorithm that ignores the resets as a low PB chance is discouraging. Encouraging the runner to reset is not something that LiveSplit should do. Also segments that haven't been reset aren't necessarily always overly good. We have the same bias in Average Segments, Median Segments and co. as well then.

**Comment by wooferzfg** [comment]
We do have a bias towards lower times in the Average Segments comparison, but that's ok because there's not much more we can do with the data we're given. I like the idea of ignoring resets for calculating PB chance and using something similar to Balanced PB.
