### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by TheTamiel** [LiveSplit/livesplit-core#216]
Currently in the root directory there is a copt of both the apache 2.0 and MIT licence.

I know they are mostly the same in what they allow, however having copies of both is a little confusing

**Comment by CryZe** [comment]
A lot, if not most Rust libraries are dual licensed under Apache 2 and MIT where the user can choose which one they want to use the library with. It might be a little confusing, but it's consistent with what most libraries are doing, so I think it makes sense to keep it this way. I'll however add a section to the README that explains the licensing.

**Comment by TheTamiel** [comment]
Cheers for the explanation
