### ISSUE TITLE
Support no_std use cases by using alloc

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/livesplit-core#223]
We long term want to support compilation of livesplit-core with just core + alloc. You'd provide your own time source as some global handler but other than that everything should mostly just work as we already see with wasm32-unknown-unknown. However most crates that we depend on probably don't support this yet, so that's probably going to be a lot of Pull Requests.

# Update

All the crates we need are sufficiently patched on forked branches. We just need to do a bunch of PRs now. Here's the super fancy results, with LiveSplit One being rendered within the world of Wind Waker: 

https://twitter.com/CryZe107/status/1158444993549414401

# Status
### Required
 - [x] base64 - Released as 0.11.0, PR is merged https://github.com/marshallpierce/rust-base64/pull/111
 - [x] derive_more - Released as 0.99.0, PR is "merged" https://github.com/JelteF/derive_more/pull/84
 - [x] odds
 - [x] ordered-float
 - [x] palette - Released as 0.5.0, PR is merged https://github.com/Ogeon/palette/pull/138
 - [x] serde
 - [x] snafu - Released as 0.6.0, PR is merged https://github.com/shepmaster/snafu/pull/138
 - [x] hashbrown - Released as 0.6.0 (There might be some bug though https://github.com/tkaitchuck/aHash/issues/17)
 - [x] libm
### Polyfilled (not required, but would be good to get rid of the polyfill)
 - [x] unicase - Released as 2.6.0, PR is merged https://github.com/seanmonstar/unicase/pull/34
 - indexmap - Released as 1.3.0, PR is merged https://github.com/bluss/indexmap/pull/106 (but serde support is missing https://github.com/bluss/indexmap/issues/109)
 - [x] chrono - Released as 0.4.10, PR is merged https://github.com/chronotope/chrono/pull/341
### Optional
 - [x] byteorder - Some IO.
 - image - Too much IO.
 - [x] livesplit-hotkey - We don't really need it, but we can easily provide an empty hotkey implementation.
 - [x] livesplit-title-abbreviations
 - parking_lot - Not really needed on no_std, does too many OS things.
 - quick-xml - Too much IO.
 - serde_json - Too much IO, but there is a PR: https://github.com/serde-rs/json/pull/516
 - utf-8 - Uses IO.

## Rendering
 - [x] euclid - Released as 0.20.6, PR is merged https://github.com/servo/euclid/pull/372
     - [x] num-traits - Released as 0.2.9, PR is merged https://github.com/rust-num/num-traits/pull/99
 - [x] ttf-parser
 - [x] rustybuzz - PR is is merged, needs a release: https://github.com/RazrFalcon/rustybuzz/pull/30
 - [x] ~~lyon - Needs a PR: https://github.com/CryZe/lyon/tree/no-std~~
    - ~~depends on euclid~~
    - [x] ~~sid - Released as 0.6.1, PR is merged https://github.com/nical/sid/pull/2~~
 - [x] ~~rusttype - Released as 0.8.0, PR is merged https://gitlab.redox-os.org/redox-os/rusttype/merge_requests/145~~
    - [x] ~~stb_truetype - Released as 0.3.0, PR is merged https://gitlab.redox-os.org/redox-os/stb_truetype-rs/merge_requests/31~~
 - [x] ~~smallvec - Released as 0.6.11, PR is merged https://github.com/servo/rust-smallvec/pull/159~~

## Software Rendering
 - [x] tiny-skia - Needs a PR
 - [x] ~~euc - Released as 0.5.0, PR is merged https://github.com/zesterer/euc/pull/12~~
    - [x] ~~vek - Released as 0.10.0, PR is merged https://github.com/yoanlcq/vek/pull/41~~
       - ~~depends on num-traits~~

**Comment by CryZe** [comment]
It seems that std::io is causing massive problems, where all our parsing, saving, serializing and co. is just not within the bounds of core and alloc. It easily could be as there barely is a reason you can't do IO without an operating system, but it's currently std only due to OS specific error codes. There is a fork called core-io, but that's going to be a ton of PRs. However there is the possibility of simply not doing any parsing, saving and serializing on no_std until then. Other problems include HashMap, Hotkeys, timing and paths, but all of these can easily be replaced (BTreeMap, mocked Hotkeys, timing handler, and a wrapper around String / &str).

**Comment by hallcristobal** [comment]
Speaking in terms of a no_std implementation, I see no real reason to have file IO directly. At most I could see implementing support for Parsing and Serializing but leave it to the developer implementing the no_std library to handle any IO needs. This would require a custom built BufReader, BufRead, Seek (possibly others) implementations which might be outside the scope of this crate though. Having livesplit-core omit this functionality until that can be safely, and correctly, implemented seems like a viable path to go down for now.

**Comment by CryZe** [comment]
Well yeah it wouldn't be File IO, it would just be the IO traits, such as Read, Write, Seek, BufRead that we can't use. And all our dependencies use them too, so that's a pain to fix in the ecosystem without no clear solution other than possibly using the fork, but that's super hacky too.

**Comment by CryZe** [comment]
All required crates are released now, so we can merge basic support in.

**Comment by CryZe** [comment]
So a ton changed in our renderer recently and we have fairly different dependencies now. rusttype is gone, lyon is gone and instead we have ttf-parser, tiny-skia and rustybuzz as dependencies now. ttf-parser is already no_std compatible, rustybuzz turned out to be trivial, so I just opened a PR. I'll have to look into tiny-skia as well, but I believe we can probably close this soon.

**Comment by CryZe** [comment]
This is blocked on proper optional feature propagation support in cargo, which is reasonably close to stabilizing.
