### ISSUE TITLE
Hotkey Support for other Systems

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/livesplit-core#24]
- [x] Windows
- [x] Linux
- [ ] macOS
- [x] emscripten

**Comment by CryZe** [comment]
Started the Linux implementation. Looks like we can only consume the hotkeys there and are not able to register them if they are already registered. If this is the case, it panics the whole application or thread due to X11's weird Error Mechanism. So this Error Mechanism needs to be turned off and hotkeys that can't be registered will just be ignored. Also you need to explicitly register hotkeys there, while on Windows you can listen to the whole keyboard. So the public API will have to change in this manner. It looks like Linux might get a similar event loop. We might not need to use a secondary thread that handles the actual closure invocation though.

**Comment by CryZe** [comment]
Something is wrong with the linux hotkeys in debug mode. The process stops without crashing in any way. This may not happen in the Linux Subsystem

**Comment by emoon** [comment]
Just a general question. Will global hotkeys be supported? (So if you have a device that would simulate global keys that should work)

**Comment by CryZe** [comment]
These are global hotkeys. There's no local hotkeys.

**Comment by CryZe** [comment]
I'm not sure if you can simulate them, that might depend on the individual API I'm using.

**Comment by emoon** [comment]
I see. I think in my case (foot pedal) it will act as a keyboard so it should hopefully be fine.

**Comment by CryZe** [comment]
I want to extend it for gamepad support eventually too (since that's something the original LiveSplit supports), so if it doesn't work, we can figure out how to make it work.

**Comment by emoon** [comment]
Cool! Sounds good :)
