### ISSUE TITLE
Implement glod Parsing

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/livesplit-core#272]
https://github.com/Tallestthomas/glod

This is the first timer with a real name collision. The other glod is an actively maintained timer based on livesplit-core + gtk.

**Comment by Eein** [comment]
o/ I'm kinda still working on mine - I chose the name for no reason whatsoever so I'm OK with changing it if there's a important reason for it. 

But honestly my project is a pet project for now until rust GUI gets to a more stable point - this is prob the 4th version I've started on but I'm really just terrible with GUI's outside of the web. Until I can actually learn how GTK and retained mode GUI's work i'm probably at a standstill. 

If there is anything I can do here to make things more convenient - feel free to let me know.

**Comment by CryZe** [comment]
I'd say this timer is dead.
