### ISSUE TITLE
Add Support for Key Combinations

### ISSUE THREAD

**Issue by xliiv** [LiveSplit/livesplit-core#280]
Is it possible to register a key combination? 
For example

```
fn main() -> Result<(), Box<dyn std::error::Error>> {
    use livesplit_hotkey::{Hook, KeyCode};
    let hook = Hook::new().unwrap();
    hook.register(KeyCode::Alt + KeyCode::Space, || println!("combo!")).unwrap();
}
```

I didn't find anything I assume it's not possible, but i also could overlooked it.

**Comment by CryZe** [comment]
Yeah you can't do that yet. Let's use this as a tracking issue for supporting this eventually.
