### ISSUE TITLE
Implement Parser for macOS timer called Splitter

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/livesplit-core#304]
https://www.reddit.com/r/speedrun/comments/f1jyzz/introducing_splitter_a_new_seedrunning_timer_for/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

Doesn‘t seem like there‘s a download link yet.

**Comment by CryZe** [comment]
I found the project. Looks like it's even using livesplit-core:
https://github.com/MichaelJBerk/Splitter

**Comment by CryZe** [comment]
It seems like they are storing the splits as a folder containing:
 - A `runInfo.json` with the following structure: [runInfo.swift](https://github.com/MichaelJBerk/Splitter/blob/1b99a2f25d4d662cad29fcc67420683bbd3c8c3b/Splitter/Data/split%20files/runInfo.swift#L12-L24)
- An optional `gameIcon.png`
- An optional folder `segIcons` that optionally contains segment icons `{}.png` with `{}` being the index of the segment starting with 0.

The overall parsing logic is [here](https://github.com/MichaelJBerk/Splitter/blob/1b99a2f25d4d662cad29fcc67420683bbd3c8c3b/Splitter/Data/split%20files/Document.swift#L174-L207)

**Comment by CryZe** [comment]
Apparently it really is just a folder with a postfix of `.split`: https://github.com/MichaelJBerk/SplitterFormats

**Comment by CryZe** [comment]
This is mostly implemented, we only need to figure out what currentTime and bestTime even mean. Are those stored as absolute times or segment times? Is bestTime the best segment time or the best split time? Is currentTime even the personal best?

**Comment by wooferzfg** [comment]
@michaeljberk could you provide insight into those questions?

**Comment by MichaelJBerk** [comment]
I’m currently in the process of reworking some things with Splitter, but the plan is to replace “current splits” with the previous time - essentially the leftmost column in LiveSplit, and “best split” will be the user’s PB. Both will be stored as absolute times (beginning of run).

**Comment by CryZe** [comment]
Can you restart the app and it will continue or why is the "delta" / current splits stored in the file format? Also is there no notion of best segments then?

**Comment by MichaelJBerk** [comment]
In the next build, “current splits” will replaced by the previous segment, and best segments will be stored as well.

**Comment by CryZe** [comment]
Closing as per https://github.com/MichaelJBerk/Splitter/wiki/.Split-Format

> Layout and run information are saved in layout.lsl and run.lss respectively, using the same formats as LiveSplit.
