### ISSUE TITLE
Implement Background based on Delta for the Timer

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/livesplit-core#380]
I completely forgot that this is an actual feature. I noticed this when I tried to import some layout file that didn't parse correctly.

https://github.com/LiveSplit/LiveSplit.Timer/commit/fbacda12e72435c4793c152fbaec98ee5b100356

**Comment by Hurricane996** [comment]
ok im messing with this. I'm trying to figure out how to represent delta gradient as a setting. It seems like the best option is to add another variant of Value, but that's a breaking change. Please advise

**Comment by CryZe** [comment]
Breaking changes are totally fine at this point 👍

**Comment by Hurricane996** [comment]
I noticed something interesting while I was fixing the alpha; vanilla livesplit doesn't consider the timer's background color at all. The gradient just goes from very transparent, devalued, desaturated version of the delta color to a more natrual version. Is that intended behavior?
