### ISSUE TITLE
`Read` on uninitialized buffer may cause UB (2 functions)

### ISSUE THREAD

**Issue by JOE1994** [LiveSplit/livesplit-core#400]
Hello :crab:,
we (Rust group @sslab-gatech) found a memory-safety/soundness issue in this crate while scanning Rust code on crates.io for potential vulnerabilities.

## Issue Description

https://github.com/LiveSplit/livesplit-core/blob/d263170c2a1bc74ff872402a5f783a4cacc2de2f/src/run/parser/llanfair.rs#L131-L145

https://github.com/LiveSplit/livesplit-core/blob/d263170c2a1bc74ff872402a5f783a4cacc2de2f/src/run/parser/llanfair.rs#L243-L246

`llanfair::read_string()` & `llanfair::parse()` creates an uninitialized buffer and passes it to user-provided `Read` implementation. This is unsound, because it allows safe Rust code to exhibit an undefined behavior (read from uninitialized memory).

[This part](https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read) from the `Read` trait documentation explains the issue:

> It is your responsibility to make sure that `buf` is initialized before calling `read`. Calling read with an uninitialized `buf` (of the kind one obtains via `MaybeUninit<T>`) is not safe, and can lead to undefined behavior.

## How to fix the issue?

The Naive & safe way to fix the issue is to always zero-initialize a buffer before lending it to a user-provided `Read` implementation. Note that this approach will add runtime performance overhead of zero-initializing the buffer.

As of Jan 2021, there is not yet an ideal fix that works in stable Rust with no performance overhead. Below are links to relevant discussions & suggestions for the fix.

* [Well-written document regarding the issue](https://paper.dropbox.com/doc/IO-Buffer-Initialization-MvytTgjIOTNpJAS6Mvw38)
* [Rust RFC 2930](https://github.com/rust-lang/rfcs/blob/master/text/2930-read-buf.md#summary)
* [nightly feature `std::io::Initializer`](https://doc.rust-lang.org/std/io/struct.Initializer.html)
* [Discussion in Rust Internals Forum](https://internals.rust-lang.org/t/uninitialized-memory/1652)

**Comment by CryZe** [comment]
Thanks, I was aware of this issue, but wasn't sure if I should wait for the safe solution or fix it. It's pretty unlikely that any Read impl actually reads from the buffer anyway. Anyways, the code isn't all that hot anyway, so it should be fine to zero initialize for now and later switch to the safe abstraction. Thanks for opening this, a PR is now up.

**Comment by JOE1994** [comment]
@CryZe Thank you so much for your quick fix!
Would you also mind publishing a new release to crates.io? (maybe `v0.11.1`)

**Comment by CryZe** [comment]
0.11 is very outdated. I think I want to mostly finish #386 and #372 and then publish v0.12.
