### ISSUE TITLE
Pointer path module offset for auto splitting on Linux

### ISSUE THREAD

**Issue by verstatx** [LiveSplit/livesplit-core#425]
While porting the Risk of Rain 2 auto splitter I noticed that, for modules with multiple entries in the maps file, the offset for pointer paths was off.

Given the following /proc/pid/maps file:
```
11f30000-11f31000 r--p 00000000 fe:00 15468804                            /Risk of Rain2_Data/Plugins/AkSoundEngine.dll
[...]
1215e000-1215f000 r--p 00227000 fe:00 15468804                           /Risk of Rain2_Data/Plugins/AkSoundEngine.dll
```
using `push_pointer_path("AkSoundEngine.dll", ...)` sets the pointer path offset to the second entry (`0x1215e000 - 0x227000`) rather than the expected `0x11f30000`. Is this behavior intended?

**Comment by TheTedder** [comment]
The autosplitting API is getting completely reworked anyway so I'll keep this in mind while working on it.

**Comment by CryZe** [comment]
Though I guess this is still kind of a problem here as the module would still be ambiguous.
