### ISSUE TITLE
Suppress repeating hotkey presses

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/livesplit-core#473]
It seems like on most platforms our hotkeys currently repeat when you keep the key pressed.

- [ ] Windows (There's no way to differentiate, we probably have to track the pressed, released status ourselves)
- [x] Linux (Easy to deal with on evdev)
- [x] macOS (The event has a `EventField::KeyboardEventAutorepeat` field that we need to take into account)
- [x] Web (The event has a `repeat` field that we need to take into account)

**Comment by CryZe** [comment]
TIL, keyboards themselves actually emit the repeats which somewhat explains why the low level keyboard hook in Windows doesn't track this for us.

**Comment by DarkRTA** [comment]
This only applies to PS/2 Keyboards. USB Keyboards don't implement this and leave it entirely up to the OS.

**Comment by CryZe** [comment]
Sure, but I assume the low level keyboard hook API is old enough (just like all the other keyboard related stuff) that it's based on PS/2.

**Comment by TheTedder** [comment]
This is pretty important for me considering I use a PS/2 keyboard!
