### ISSUE TITLE
Fix unreachable code when parsing Font name from original LiveSplit

### ISSUE THREAD

**Issue by KaDiWa4** [LiveSplit/livesplit-core#486]
In fn `layout::parser::font`, there is a long list of `else if`s, including the following two:
```
} else if token.eq_ignore_ascii_case("normal") {
    weight = FontWeight::Normal;
}
```
and
```
} else if token.eq_ignore_ascii_case("normal") {
    stretch = FontStretch::Normal;
}
```
which both have the same condition, so the second one cannot be reached ([source code]).
I don't know what the intended behavior would be.

[source code]: https://github.com/LiveSplit/livesplit-core/blob/master/src/layout/parser/mod.rs#L381-L410

**Comment by CryZe** [comment]
Oh that is indeed true. I guess both checks can be removed in that case as Normal is the default for both anyway.
