### ISSUE TITLE
Implementations

### ISSUE THREAD

**Issue by ShalokShalom** [LiveSplit/livesplit-core#529]
Is there a list of all the known implementations?

So, to find alternatives like Livesplit One and similar. 

I am on Linux and trying to find a solution.

**Comment by CryZe** [comment]
There's a bunch of not so serious implementations (GBA, Wind Waker, Minecraft, Super Mario 64, ...), but the most serious ones are:
- [LiveSplit One Web](https://github.com/LiveSplit/LiveSplitOne)
- [LiveSplit One Desktop Prototype](https://github.com/CryZe/livesplit-one-desktop)
- [LiveSplit One OBS Plugin](https://github.com/CryZe/obs-livesplit-one)
- [chronos Terminal Timer](https://github.com/DarkRTA/chronos)
- [annelid](https://github.com/dagit/annelid)
