### ISSUE TITLE
Curly bracket in comment breaks auto-splitter code

### ISSUE THREAD

**Issue by Gyoshi** [LiveSplit/livesplit-core#620]
```Csharp
startup {
	vars.test = 5;
	// this -> {
}

init {
}
```
The above code gives 'startup' method compilation errors due to the curly bracket in the commented-out line. Can lead to a pretty frustrating debugging experience when you don't expect comments to affect anything

**Comment by Jujstme** [comment]
Duplicate of https://github.com/LiveSplit/LiveSplit.ScriptableAutoSplit/issues/55

**Comment by CryZe** [comment]
This is the wrong repository, thus I'm closing this.
