### ISSUE TITLE
[ASR] Log to file

### ISSUE THREAD

**Issue by apple1417** [LiveSplit/livesplit-core#696]
It would be nice if all debug messages were logged to a file, so you wouldn't need to actively be running the debugger to tell what your autosplitter is doing, and so you could more easily get debug info back from a regular user.

Not sure if this is the right repo for this, since you probably want it to be configured by the app linking against livesplit core.

**Comment by CryZe** [comment]
Yeah this isn't the right repository. From the perspective of lsc, the messages are just forwarded to the application. LiveSplit One for example logs everything to a file. So this would need to be changed in the original LiveSplit.
