### ISSUE TITLE
Hotkeys do not work when num lock is active

### ISSUE THREAD

**Issue by tp971** [LiveSplit/livesplit-core#711]
On my system, hotkeys do not work at all when num lock is active. I used the desktop prototype (https://github.com/LiveSplit/livesplit-core). Here is some maybe relevant information:

OS: Debian 12.1 "Bookworm"
DE: Xfce 4.18
rustc: 1.71.1

**Comment by CryZe** [comment]
Alright, with some debugging help with @Pheenoh we figured out that the way we register the modifiers (and honestly the only way X11 seems to directly support this) means that no other modifier combination is valid for the hotkey. And unfortunately having the numlock on counts as a modifier. I'll look into ways to fix this.

**Comment by TheTedder** [comment]
You could have an option to always register two hotkeys—one with and without numlock—and then just coalesce them.

**Comment by CryZe** [comment]
Yeah the solution is probably to register every combination that we are not interested in. It just combinatoricly "explodes" because of num lock, scroll lock, caps lock and co.
