### ISSUE TITLE
Ensure whitespace isn't getting trimmed when saving / parsing

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/livesplit-core#77]
XML is not the greatest format in that regard, but we should try to ensure that no information is lost. It may already work correctly, it may not and there may not be a solution. So this needs to be checked.

**Comment by CryZe** [comment]
It turns out that both livesplit-core and the original LiveSplit are indeed trimming whitespace. While this means that we ported it correctly, it also means that lss is not lossless, which we might want to fix.

**Comment by CryZe** [comment]
@wooferzfg Do you think we should just close this? Both XML and HTML work like this by default and it didn't really cause any problems so far.

**Comment by wooferzfg** [comment]
In that case, yeah.
