### ISSUE TITLE
Only modifier keys get registered on MacOS

### ISSUE THREAD

**Issue by M1KUS3Q** [LiveSplit/livesplit-core#778]
When running this code on mac (with both accessibility and input monitoring enabled for terminal and Vscode, where I am running the program):
```rs
    let hook = Hook::new().unwrap();
    hook.register(
        Hotkey {
            key_code: KeyCode::KeyP,
            modifiers: Modifiers::empty(),
        },
        || println!("pressed key"),
    )
    .unwrap();
```
No keys get registered. I found that putting Modifier keys in the key_code variable does work, and I can combine e.g. RightAlt + Modifiers::META. Any non-modifier key does not get registered.

**Comment by CryZe** [comment]
I'm assuming this is #659. Can you try with the master branch?

**Comment by M1KUS3Q** [comment]
Downloaded the livesplit-hotkey crate from master and replaced the dependency in my code, and now no events get sent at all. Tried with regular keys, as well as modifier keys, no events seem to go through.

**Comment by M1KUS3Q** [comment]
Updated to MacOS 14.3.1 and it started working. Thanks for help.
